// hpsdr_p1.c — openHPSDR Protocol 1 interface for sBitx
//
// Implements a minimal P1 SDR server that integrates with the sBitx audio pipeline:
//
//   RX path: sBitx audio thread calls hpsdr_send_iq() with 96kHz baseband IQ.
//            Samples are low-pass filtered and decimated 2:1 to 48kHz, then
//            packed into EP6 UDP frames and streamed to the connected SDR client.
//
//   TX path: The background poll thread receives EP2 UDP frames from the SDR client.
//            48kHz TX IQ samples are extracted, interpolated back to 96kHz, and
//            written into a lock-free ring buffer for sound_process() to consume.
//            TX is triggered automatically when IQ data starts arriving and
//            released 500ms after the last sample — no explicit PTT parsing needed.
//
//   Control: Discovery, start/stop, and frequency commands are handled by the
//            poll thread. T/R switching is dispatched to the GTK main thread via
//            g_idle_add() to stay clear of the audio and UI threads.
//
// Code generated by copilot AI as a demo only ... good luck!  Mike/KB2ML

#include <arpa/inet.h>
#include <gtk/gtk.h>
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <unistd.h>

#define HPSDR_PORT 1024
#define HPSDR_PKT_SIZE 1032
#define SAMPLES_PER_PACKET 126

static int hpsdr_sock = -1;
static struct sockaddr_in stream_dest;
static volatile int client_active = 0;
static volatile int running = 0;
static uint32_t tx_seq = 0;
static pthread_t poll_thread;

// IQ accumulation buffer for 126 samples (48kHz)
static double iq_buf_i[SAMPLES_PER_PACKET];
static double iq_buf_q[SAMPLES_PER_PACKET];
static int iq_buf_count = 0;
static double hpsdr_iq_gain = 30.0; // add gain to I and Q data going out

// Filter state for the 24kHz LPF (stores the last sample of the previous block)
static double last_i = 0.0;
static double last_q = 0.0;

extern void remote_execute(char *command);
extern int freq_hdr;
extern int in_tx;
extern void tr_switch(int tx_on);
extern void tx_on(int trigger);
extern void tx_off(void);
#define TX_SOFT 2

// =============================================================================
// GTK main-thread callbacks for T/R switching
//
// TX and RX transitions must run on the GTK main thread to avoid races with
// the UI and CW keyer.  These one-shot callbacks are dispatched via g_idle_add()
// from the poll thread whenever incoming IQ data starts or stops.
// =============================================================================

static gboolean hpsdr_tx_on_idle(gpointer data) {
  (void)data;
  if (!in_tx)
    tx_on(TX_SOFT);
  return G_SOURCE_REMOVE; // one-shot
}

static gboolean hpsdr_tx_off_idle(gpointer data) {
  (void)data;
  printf("hpsdr_tx_off_idle: in_tx=%d (extern)\n", in_tx);
  tx_off();
  printf("hpsdr_tx_off_idle: after tx_off, in_tx=%d (extern)\n", in_tx);
  return G_SOURCE_REMOVE;
}

// =============================================================================
// TX IQ ring buffer
//
// Receives 48kHz IQ from the remote SDR client (via the poll thread) and makes
// 96kHz samples available to sound_process() on the audio thread.
//
// The poll thread writes via tx_iq_push_48k(), which also performs 2× linear
// interpolation (48k → 96k).  The audio thread reads via hpsdr_get_tx_iq().
//
// TX is driven entirely by data flow:
//   - First arriving sample schedules tx_on() via g_idle_add().
//   - If no new samples arrive for TX_IQ_TIMEOUT_MS, hpsdr_tx_iq_active()
//     returns 0 and the watchdog schedules tx_off().
//
// Ring size is a power of 2 for cheap modulo masking.  At 96kHz, 8192 samples
// is ~85ms — enough to absorb network jitter without audible latency.
// =============================================================================

#define TX_IQ_RING_SIZE 8192 // must be power of 2, ~85 ms at 96 kHz
#define TX_IQ_RING_MASK (TX_IQ_RING_SIZE - 1)

static double tx_iq_ring_i[TX_IQ_RING_SIZE];
static double tx_iq_ring_q[TX_IQ_RING_SIZE];
static volatile int tx_iq_wr = 0; // written by poll thread
static volatile int tx_iq_rd = 0; // read by audio thread

// Timeout: if no TX IQ arrives for this many ms, declare inactive
#define TX_IQ_TIMEOUT_MS 500
static volatile unsigned long tx_iq_last_time_ms = 0;
static volatile int hpsdr_tx_data_active = 0;

// Watchdog: timestamp of the last EP2 packet received from the remote app.
// Updated on every EP2 packet, regardless of MOX state.
// If we are in TX and this goes stale, the watchdog fires tx_off().

// Previous sample for the 2× interpolation filter
static double tx_up_prev_i = 0.0;
static double tx_up_prev_q = 0.0;

static unsigned long millis_now(void) {
  struct timespec ts;
  clock_gettime(CLOCK_MONOTONIC, &ts);
  return (unsigned long)(ts.tv_sec * 1000 + ts.tv_nsec / 1000000);
}

// Write one 48 kHz sample pair into the ring as two 96 kHz samples
// using linear interpolation (simple half-band upsample).
static void tx_iq_push_48k(double i_val, double q_val) {
  // Interpolated mid-point sample (insert between previous and current)
  double mid_i = 0.5 * (tx_up_prev_i + i_val);
  double mid_q = 0.5 * (tx_up_prev_q + q_val);

  int wr = tx_iq_wr;

  tx_iq_ring_i[wr & TX_IQ_RING_MASK] = mid_i;
  tx_iq_ring_q[wr & TX_IQ_RING_MASK] = mid_q;
  wr++;

  tx_iq_ring_i[wr & TX_IQ_RING_MASK] = i_val;
  tx_iq_ring_q[wr & TX_IQ_RING_MASK] = q_val;
  wr++;

  tx_iq_wr = wr;
  tx_up_prev_i = i_val;
  tx_up_prev_q = q_val;
  tx_iq_last_time_ms = millis_now();
  if (!hpsdr_tx_data_active) {
    hpsdr_tx_data_active = 1;
    // DEBUG CODE
    printf("hpsdr: first non-zero IQ — triggering TX (i=%.6f q=%.6f)\n", i_val, q_val);
    g_idle_add(hpsdr_tx_on_idle, NULL);
  }
}

// =============================================================================
// Public API — called by sbitx.c audio thread
//
// hpsdr_tx_iq_active() — returns 1 if a client is connected and TX IQ samples
//                         have arrived within the last TX_IQ_TIMEOUT_MS ms.
//                         Used by sound_process() to decide whether to switch
//                         the audio pipeline to the remote TX IQ source.
//
// hpsdr_get_tx_iq()    — drains up to max_samples 96kHz IQ pairs from the ring
//                         buffer into the caller's arrays.  Returns the number
//                         of samples actually copied.
// =============================================================================

int hpsdr_tx_iq_active(void) {
  if (!client_active)
    return 0;
  // Check that we received TX IQ data recently
  unsigned long now = millis_now();
  if (now - tx_iq_last_time_ms > TX_IQ_TIMEOUT_MS)
    return 0;
  // And that there is actually data in the ring
  return ((tx_iq_wr - tx_iq_rd) > 0);
}

int hpsdr_get_tx_iq(double *out_i, double *out_q, int max_samples) {
  int rd = tx_iq_rd;
  int avail = tx_iq_wr - rd;
  if (avail < 0)
    avail = 0;
  int n = (avail < max_samples) ? avail : max_samples;

  for (int k = 0; k < n; k++) {
    out_i[k] = tx_iq_ring_i[(rd + k) & TX_IQ_RING_MASK];
    out_q[k] = tx_iq_ring_q[(rd + k) & TX_IQ_RING_MASK];
  }
  tx_iq_rd = rd + n;
  return n;
}

// =============================================================================
// Watchdog — runs every 250ms on the GTK main thread (via g_timeout_add)
//
// Guards against the radio being left stuck in TX if the remote SDR application
// crashes, closes, or stops sending IQ data without a clean stop handshake.
//
// If hpsdr_tx_data_active is set but no IQ data has arrived for 500ms,
// the transmitter is forced back to RX and the ring buffer is flushed.
// =============================================================================

static gboolean hpsdr_watchdog(gpointer data) {
  (void)data;
  if (!running)
    return G_SOURCE_REMOVE;

  if (hpsdr_tx_data_active && (millis_now() - tx_iq_last_time_ms > 500)) {
    printf("hpsdr watchdog: IQ data gone >500ms — forcing RX\n");
    hpsdr_tx_data_active = 0;
    tx_iq_wr = 0;
    tx_iq_rd = 0;
    tx_up_prev_i = 0.0;
    tx_up_prev_q = 0.0;
    tx_off();
  }

  return G_SOURCE_CONTINUE;
}

// =============================================================================
// RX IQ packet construction — EP6 frames to the remote SDR client
//
// build_and_send_packet() assembles one 1032-byte EP6 UDP datagram containing
// two 512-byte P1 frames, each carrying 63 IQ sample slots (24-bit I + 24-bit Q)
// and a C&C header that reports the current VFO frequency and TX/RX state.
//
// hpsdr_send_iq() is called by the sBitx audio thread at 96kHz.  It applies a
// 3-tap half-band FIR (cutoff ~24kHz) and decimates 2:1 to 48kHz before
// accumulating samples into the packet buffer.
// =============================================================================

static void build_and_send_packet(void) {
  uint8_t pkt[HPSDR_PKT_SIZE];
  memset(pkt, 0, sizeof(pkt));

  // EP6 Header
  pkt[0] = 0xEF;
  pkt[1] = 0xFE;
  pkt[2] = 0x01;
  pkt[3] = 0x06;
  pkt[4] = (tx_seq >> 24) & 0xFF;
  pkt[5] = (tx_seq >> 16) & 0xFF;
  pkt[6] = (tx_seq >> 8) & 0xFF;
  pkt[7] = tx_seq & 0xFF;

  uint32_t seq_for_cc = tx_seq++;

  // Two 512-byte frames
  for (int frame = 0; frame < 2; frame++) {
    uint8_t *fp = pkt + 8 + frame * 512;

    // Sync bytes
    fp[0] = 0x7F;
    fp[1] = 0x7F;
    fp[2] = 0x7F;

    // C&C control bytes (cycle through C0 addresses 0 and 1)
    int cc_addr = (seq_for_cc * 2 + frame) % 2;
    fp[3] = (cc_addr << 1) | (in_tx ? 1 : 0);

    if (cc_addr == 0) {
      fp[4] = (freq_hdr >> 24) & 0xFF;
      fp[5] = (freq_hdr >> 16) & 0xFF;
      fp[6] = (freq_hdr >> 8) & 0xFF;
      fp[7] = freq_hdr & 0xFF;
    } else if (cc_addr == 1) {
      fp[4] = 0x00; // 48 kHz, no ADC overflow
      fp[5] = 0x00;
      fp[6] = 0x00;
      fp[7] = 0x00;
    }

    // 63 IQ samples per frame
    for (int s = 0; s < 63; s++) {
      int idx = frame * 63 + s;
      uint8_t *sp = fp + 8 + s * 8;

      int32_t i_val = (int32_t)(iq_buf_i[idx] * 559240.0);
      if (i_val > 8388607)
        i_val = 8388607;
      if (i_val < -8388608)
        i_val = -8388608;

      int32_t q_val = (int32_t)(iq_buf_q[idx] * 559240.0);
      if (q_val > 8388607)
        q_val = 8388607;
      if (q_val < -8388608)
        q_val = -8388608;

      // Pack I
      sp[0] = (i_val >> 16) & 0xFF;
      sp[1] = (i_val >> 8) & 0xFF;
      sp[2] = i_val & 0xFF;

      // Pack Q
      sp[3] = (q_val >> 16) & 0xFF;
      sp[4] = (q_val >> 8) & 0xFF;
      sp[5] = q_val & 0xFF;

      // Mic sample (unused)
      sp[6] = 0;
      sp[7] = 0;
    }
  }

  if (client_active) {
    sendto(hpsdr_sock, pkt, sizeof(pkt), 0, (struct sockaddr *)&stream_dest, sizeof(stream_dest));
  }
}

// --- Main Audio Thread Hook -------------------------------------------------

// Called continuously with 96kHz samples from the RX processing chain.
// Applies a 24kHz half-band LPF to prevent aliasing, then decimates 2:1.
void hpsdr_send_iq(double *i_samples, double *q_samples, int n) {
  if (!client_active || hpsdr_sock < 0)
    return;

  for (int k = 0; k < n; k += 2) {
    double filt_i, filt_q;

    // Simple 3-tap FIR half-band filter: 0.25*z^-1 + 0.5*z^0 + 0.25*z^1
    // Cuts off accurately at Fs/4 (24kHz)
    if (k == 0) {
      filt_i = 0.25 * last_i + 0.5 * i_samples[0] + 0.25 * i_samples[1];
      filt_q = 0.25 * last_q + 0.5 * q_samples[0] + 0.25 * q_samples[1];
    } else if (k + 1 < n) {
      filt_i = 0.25 * i_samples[k - 1] + 0.5 * i_samples[k] + 0.25 * i_samples[k + 1];
      filt_q = 0.25 * q_samples[k - 1] + 0.5 * q_samples[k] + 0.25 * q_samples[k + 1];
    } else {
      // Edge case handling if 'n' isn't even, though it usually is 1024
      filt_i = i_samples[k];
      filt_q = q_samples[k];
    }

    iq_buf_i[iq_buf_count] = filt_i * hpsdr_iq_gain;
    iq_buf_q[iq_buf_count] = filt_q * hpsdr_iq_gain;
    iq_buf_count++;

    if (iq_buf_count >= SAMPLES_PER_PACKET) {
      build_and_send_packet();
      iq_buf_count = 0;
    }
  }

  // Save final samples for the next block's filter calculation
  if (n > 0) {
    last_i = i_samples[n - 1];
    last_q = q_samples[n - 1];
  }
}

// =============================================================================
// Protocol 1 command handler — EP2 packets from the remote SDR client
//
// Three packet types are handled:
//
//   0x02  Discovery — reply with board identity (emulates a Hermes SDR).
//         Reports "in-use" if a different client is already streaming.
//
//   0x04  Start/Stop — arms or disarms the IQ stream.  On start, all TX state
//         is reset.  On stop, any active transmission is safely terminated.
//
//   0x01  EP2 host commands — each 1032-byte packet contains two P1 frames.
//         Each frame is parsed for:
//           • C&C address 0x02: remote VFO frequency → forwarded to sBitx
//           • TX IQ audio samples → extracted and pushed into the ring buffer
//             (data-driven TX: arrival of samples triggers transmit automatically)
//
// Called from hpsdr_poll_thread() — runs entirely on the background thread.
// Any T/R transitions are dispatched to the GTK main thread via g_idle_add().
// =============================================================================

// Extract TX IQ audio samples from an EP2 frame.
// Each frame has 63 audio sample slots at offsets 8..511,
// each slot is 8 bytes: I(16-bit) Q(16-bit) + 2 padding bytes in P1 TX format.
// SDRConsole sends TX IQ as two 16-bit signed values per slot.
static void extract_tx_iq_from_frame(uint8_t *fp) {
  for (int s = 0; s < 63; s++) {
    uint8_t *sp = fp + 8 + s * 8;

    // TX IQ is at bytes 4-5 (I) and 6-7 (Q) — NOT bytes 0-3 (mic audio)
    int16_t i_raw = (int16_t)((sp[4] << 8) | sp[5]);
    int16_t q_raw = (int16_t)((sp[6] << 8) | sp[7]);

    if (s == 0)
      printf("hpsdr EP2 IQ: i_raw=%d q_raw=%d\n", i_raw, q_raw);

    if (i_raw == 0 && q_raw == 0)
      continue;

    double i_val = i_raw / 32768.0;
    double q_val = q_raw / 32768.0;

    tx_iq_push_48k(i_val, q_val);
  }
}

static void handle_command(uint8_t *buf, int len, struct sockaddr_in *sender) {
  if (len < 4 || buf[0] != 0xEF || buf[1] != 0xFE)
    return;

  switch (buf[2]) {
  case 0x02: // Discovery request
  {
    uint8_t reply[64];
    memset(reply, 0, sizeof(reply));
    reply[0] = 0xEF;
    reply[1] = 0xFE;
    reply[2] = 0x02;

    // 0x00 = available, 0x02 = in-use
    int same_client = (sender->sin_addr.s_addr == stream_dest.sin_addr.s_addr);
    reply[3] = (client_active && !same_client) ? 0x02 : 0x00;

    // Fake MAC address & board info (Hermes)
    reply[4] = 0x00;
    reply[5] = 0x1C;
    reply[6] = 0xC0;
    reply[7] = 0xA2;
    reply[8] = 0x22;
    reply[9] = 0x5B;
    reply[10] = 0x06; // Board type
    reply[11] = 0x25; // Protocol version

    sendto(hpsdr_sock, reply, sizeof(reply), 0, (struct sockaddr *)sender, sizeof(*sender));
  } break;

  case 0x04: // Start / stop streaming
    if (buf[3] & 0x01) {
      stream_dest = *sender;
      tx_seq = 0;
      iq_buf_count = 0;
      // Reset TX IQ state on new connection
      tx_iq_wr = 0;
      tx_iq_rd = 0;
      tx_up_prev_i = 0.0;
      tx_up_prev_q = 0.0;
      hpsdr_tx_data_active = 0; // reset data-driven TX state on new connection
      client_active = 1;
      printf("hpsdr: streaming STARTED to %s:%d\n", inet_ntoa(stream_dest.sin_addr),
             ntohs(stream_dest.sin_port));
    } else {
      client_active = 0;
      printf("hpsdr: streaming STOPPED\n");

      // Safety catch: If the client disconnected while transmitting, turn it off
      if (hpsdr_tx_data_active) {
        hpsdr_tx_data_active = 0;
        g_idle_add(hpsdr_tx_off_idle, NULL);
      }
    }
    break;

  case 0x01: // EP2 host commands
    if (!client_active) break;
    if (len >= HPSDR_PKT_SIZE) {
      for (int frame = 0; frame < 2; frame++) {
        uint8_t *fp = buf + 8 + frame * 512;
        if (fp[0] != 0x7F || fp[1] != 0x7F || fp[2] != 0x7F)
          continue;

        int c0 = fp[3];
        int addr = (c0 >> 1) & 0x1F;
        int mox = c0 & 0x01;   // ← MOX bit from SDR Console

        if (addr == 0x02) {
          int f = (fp[4] << 24) | (fp[5] << 16) | (fp[6] << 8) | fp[7];
          if (f > 0 && f != freq_hdr) {
            printf("hpsdr: remote set freq %d Hz\n", f);
            char cmd[50];
            sprintf(cmd, "freq %d", f);
            remote_execute(cmd);
          }
        }

        // Only push IQ into the ring when SDR Console has MOX set.
        // This prevents connect-time noise from falsely triggering TX.
        if (mox)
          extract_tx_iq_from_frame(fp);
      }
    }
    break;
  }
}

static void *hpsdr_poll_thread(void *arg) {
  (void)arg;
  uint8_t buf[2048];
  struct sockaddr_in sender;
  socklen_t sender_len;

  while (running) {
    sender_len = sizeof(sender);
    int n = recvfrom(hpsdr_sock, buf, sizeof(buf), 0, (struct sockaddr *)&sender, &sender_len);
    if (n > 0) {
      handle_command(buf, n, &sender);
    }
  }
  return NULL;
}

// =============================================================================
// Lifecycle API — called from sbitx.c at startup and shutdown
//
// hpsdr_init()  — opens and binds the UDP socket on HPSDR_PORT (1024).
//                 Sets a 200ms receive timeout so the poll thread can exit
//                 cleanly when running is cleared.  Returns 0 on success, -1
//                 on socket or bind failure.
//
// hpsdr_poll()  — called once from the main loop after hpsdr_init().
//                 Spawns the background poll thread and registers the watchdog
//                 timer on the GTK main loop.  Safe to call repeatedly.
//
// hpsdr_stop()  — clears the running flag and closes the socket.  The poll
//                 thread will exit on its next receive timeout.
// =============================================================================

int hpsdr_init(void) {
  hpsdr_sock = socket(AF_INET, SOCK_DGRAM, 0);
  if (hpsdr_sock < 0)
    return -1;

  int optval = 1;
  setsockopt(hpsdr_sock, SOL_SOCKET, SO_REUSEADDR, &optval, sizeof(optval));
  setsockopt(hpsdr_sock, SOL_SOCKET, SO_BROADCAST, &optval, sizeof(optval));

  struct sockaddr_in addr;
  memset(&addr, 0, sizeof(addr));
  addr.sin_family = AF_INET;
  addr.sin_port = htons(HPSDR_PORT);
  addr.sin_addr.s_addr = htonl(INADDR_ANY);

  if (bind(hpsdr_sock, (struct sockaddr *)&addr, sizeof(addr)) < 0) {
    close(hpsdr_sock);
    hpsdr_sock = -1;
    return -1;
  }

  struct timeval tv = {.tv_sec = 0, .tv_usec = 200000};
  setsockopt(hpsdr_sock, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));

  running = 1;
  return 0;
}

void hpsdr_stop(void) {
  running = 0;
  client_active = 0;

  if (hpsdr_sock >= 0) {
    close(hpsdr_sock);
    hpsdr_sock = -1;
  }
}

int hpsdr_is_connected(void) { return client_active; }

void hpsdr_poll(void) {
  static int started = 0;
  if (!started && running) {
    pthread_create(&poll_thread, NULL, hpsdr_poll_thread, NULL);
    g_timeout_add(250, hpsdr_watchdog, NULL); // fire every 250 ms on GTK thread
    started = 1;
  }
}
