// hpsdr_p1.c — Minimal openHPSDR Protocol 1 IQ streamer for sBitx

// Sends baseband IQ from sBitx to a Protocol 1 SDR client on our network.
// Packets are sent inline without flow control or mutexes.
// Decimates 96k input to 48k using a simple 24kHz LPF filter.
// I and Q values received are scaled back up to 96k
// Code generated by copilot AI as a demo only ... good luck!  Mike/KB2ML

#include <arpa/inet.h>
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <unistd.h>
#include <gtk/gtk.h>

#define HPSDR_PORT 1024
#define HPSDR_PKT_SIZE 1032
#define SAMPLES_PER_PACKET 126

static int hpsdr_sock = -1;
static struct sockaddr_in stream_dest;
static volatile int client_active = 0;
static volatile int running = 0;
static uint32_t tx_seq = 0;
static pthread_t poll_thread;
static volatile int remote_mox = 0;

// IQ accumulation buffer for 126 samples (48kHz)
static double iq_buf_i[SAMPLES_PER_PACKET];
static double iq_buf_q[SAMPLES_PER_PACKET];
static int iq_buf_count = 0;
static double hpsdr_iq_gain = 30.0; // add gain to I and Q data going out

// Filter state for the 24kHz LPF (stores the last sample of the previous block)
static double last_i = 0.0;
static double last_q = 0.0;

extern void remote_execute(char *command);
extern int freq_hdr;
extern int in_tx;
extern void tr_switch(int tx_on);
extern void tx_on(int trigger);
extern void tx_off(void);
#define TX_SOFT 2

static gboolean hpsdr_tx_on_idle(gpointer data) {
    (void)data;
    if (!in_tx)
        tx_on(TX_SOFT);
    return G_SOURCE_REMOVE;  // one-shot
}

static gboolean hpsdr_tx_off_idle(gpointer data) {
    (void)data;
    printf("hpsdr_tx_off_idle: in_tx=%d (extern)\n", in_tx);
    tx_off();
    printf("hpsdr_tx_off_idle: after tx_off, in_tx=%d (extern)\n", in_tx);
    return G_SOURCE_REMOVE;
}

// =============================================================================
// TX IQ ring buffer — receives 48kHz IQ from remote SDR client,
// upsamples to 96kHz, and makes it available to sound_process().
// =============================================================================

#define TX_IQ_RING_SIZE 8192 // must be power of 2, ~85 ms at 96 kHz
#define TX_IQ_RING_MASK (TX_IQ_RING_SIZE - 1)

static double tx_iq_ring_i[TX_IQ_RING_SIZE];
static double tx_iq_ring_q[TX_IQ_RING_SIZE];
static volatile int tx_iq_wr = 0; // written by poll thread
static volatile int tx_iq_rd = 0; // read by audio thread

// Timeout: if no TX IQ arrives for this many ms, declare inactive
#define TX_IQ_TIMEOUT_MS 500
static volatile unsigned long tx_iq_last_time_ms = 0;

// Previous sample for the 2× interpolation filter
static double tx_up_prev_i = 0.0;
static double tx_up_prev_q = 0.0;

static unsigned long millis_now(void) {
  struct timespec ts;
  clock_gettime(CLOCK_MONOTONIC, &ts);
  return (unsigned long)(ts.tv_sec * 1000 + ts.tv_nsec / 1000000);
}

// Write one 48 kHz sample pair into the ring as two 96 kHz samples
// using linear interpolation (simple half-band upsample).
static void tx_iq_push_48k(double i_val, double q_val) {
  // Interpolated mid-point sample (insert between previous and current)
  double mid_i = 0.5 * (tx_up_prev_i + i_val);
  double mid_q = 0.5 * (tx_up_prev_q + q_val);

  int wr = tx_iq_wr;

  tx_iq_ring_i[wr & TX_IQ_RING_MASK] = mid_i;
  tx_iq_ring_q[wr & TX_IQ_RING_MASK] = mid_q;
  wr++;

  tx_iq_ring_i[wr & TX_IQ_RING_MASK] = i_val;
  tx_iq_ring_q[wr & TX_IQ_RING_MASK] = q_val;
  wr++;

  tx_iq_wr = wr;
  tx_up_prev_i = i_val;
  tx_up_prev_q = q_val;
  tx_iq_last_time_ms = millis_now();
}

// --- Public API for sbitx.c --------------------------------------------------

int hpsdr_tx_iq_active(void) {
  if (!client_active)
    return 0;
  // Check that we received TX IQ data recently
  unsigned long now = millis_now();
  if (now - tx_iq_last_time_ms > TX_IQ_TIMEOUT_MS)
    return 0;
  // And that there is actually data in the ring
  return ((tx_iq_wr - tx_iq_rd) > 0);
}

int hpsdr_get_tx_iq(double *out_i, double *out_q, int max_samples) {
  int rd = tx_iq_rd;
  int avail = tx_iq_wr - rd;
  if (avail < 0)
    avail = 0;
  int n = (avail < max_samples) ? avail : max_samples;

  for (int k = 0; k < n; k++) {
    out_i[k] = tx_iq_ring_i[(rd + k) & TX_IQ_RING_MASK];
    out_q[k] = tx_iq_ring_q[(rd + k) & TX_IQ_RING_MASK];
  }
  tx_iq_rd = rd + n;
  return n;
}

// =============================================================================
// --- Packet construction & inline transmission (unchanged) -------------------
// =============================================================================

static void build_and_send_packet(void) {
  uint8_t pkt[HPSDR_PKT_SIZE];
  memset(pkt, 0, sizeof(pkt));

  // EP6 Header
  pkt[0] = 0xEF;
  pkt[1] = 0xFE;
  pkt[2] = 0x01;
  pkt[3] = 0x06;
  pkt[4] = (tx_seq >> 24) & 0xFF;
  pkt[5] = (tx_seq >> 16) & 0xFF;
  pkt[6] = (tx_seq >> 8) & 0xFF;
  pkt[7] = tx_seq & 0xFF;

  uint32_t seq_for_cc = tx_seq++;

  // Two 512-byte frames
  for (int frame = 0; frame < 2; frame++) {
    uint8_t *fp = pkt + 8 + frame * 512;

    // Sync bytes
    fp[0] = 0x7F;
    fp[1] = 0x7F;
    fp[2] = 0x7F;

    // C&C control bytes (cycle through C0 addresses 0 and 1)
    int cc_addr = (seq_for_cc * 2 + frame) % 2;
    fp[3] = (cc_addr << 1) | (in_tx ? 1 : 0);

    if (cc_addr == 0) {
      fp[4] = (freq_hdr >> 24) & 0xFF;
      fp[5] = (freq_hdr >> 16) & 0xFF;
      fp[6] = (freq_hdr >> 8) & 0xFF;
      fp[7] = freq_hdr & 0xFF;
    } else if (cc_addr == 1) {
      fp[4] = 0x00; // 48 kHz, no ADC overflow
      fp[5] = 0x00;
      fp[6] = 0x00;
      fp[7] = 0x00;
    }

    // 63 IQ samples per frame
    for (int s = 0; s < 63; s++) {
      int idx = frame * 63 + s;
      uint8_t *sp = fp + 8 + s * 8;

      int32_t i_val = (int32_t)(iq_buf_i[idx] * 559240.0);
      if (i_val > 8388607)
        i_val = 8388607;
      if (i_val < -8388608)
        i_val = -8388608;

      int32_t q_val = (int32_t)(iq_buf_q[idx] * 559240.0);
      if (q_val > 8388607)
        q_val = 8388607;
      if (q_val < -8388608)
        q_val = -8388608;

      // Pack I
      sp[0] = (i_val >> 16) & 0xFF;
      sp[1] = (i_val >> 8) & 0xFF;
      sp[2] = i_val & 0xFF;

      // Pack Q
      sp[3] = (q_val >> 16) & 0xFF;
      sp[4] = (q_val >> 8) & 0xFF;
      sp[5] = q_val & 0xFF;

      // Mic sample (unused)
      sp[6] = 0;
      sp[7] = 0;
    }
  }

  if (client_active) {
    sendto(hpsdr_sock, pkt, sizeof(pkt), 0, (struct sockaddr *)&stream_dest, sizeof(stream_dest));
  }
}

// --- Main Audio Thread Hook -------------------------------------------------

// Called continuously with 96kHz samples from the RX processing chain.
// Applies a 24kHz half-band LPF to prevent aliasing, then decimates 2:1.
void hpsdr_send_iq(double *i_samples, double *q_samples, int n) {
  if (!client_active || hpsdr_sock < 0)
    return;

  for (int k = 0; k < n; k += 2) {
    double filt_i, filt_q;

    // Simple 3-tap FIR half-band filter: 0.25*z^-1 + 0.5*z^0 + 0.25*z^1
    // Cuts off accurately at Fs/4 (24kHz)
    if (k == 0) {
      filt_i = 0.25 * last_i + 0.5 * i_samples[0] + 0.25 * i_samples[1];
      filt_q = 0.25 * last_q + 0.5 * q_samples[0] + 0.25 * q_samples[1];
    } else if (k + 1 < n) {
      filt_i = 0.25 * i_samples[k - 1] + 0.5 * i_samples[k] + 0.25 * i_samples[k + 1];
      filt_q = 0.25 * q_samples[k - 1] + 0.5 * q_samples[k] + 0.25 * q_samples[k + 1];
    } else {
      // Edge case handling if 'n' isn't even, though it usually is 1024
      filt_i = i_samples[k];
      filt_q = q_samples[k];
    }

    iq_buf_i[iq_buf_count] = filt_i * hpsdr_iq_gain;
    iq_buf_q[iq_buf_count] = filt_q * hpsdr_iq_gain;
    iq_buf_count++;

    if (iq_buf_count >= SAMPLES_PER_PACKET) {
      build_and_send_packet();
      iq_buf_count = 0;
    }
  }

  // Save final samples for the next block's filter calculation
  if (n > 0) {
    last_i = i_samples[n - 1];
    last_q = q_samples[n - 1];
  }
}

// --- Command and Discovery (Background Thread) ------------------------------

// Extract TX IQ audio samples from an EP2 frame.
// Each frame has 63 audio sample slots at offsets 8..511,
// each slot is 8 bytes: I(16-bit) Q(16-bit) + 2 padding bytes in P1 TX format.
// SDRConsole sends TX IQ as two 16-bit signed values per slot.
static void extract_tx_iq_from_frame(uint8_t *fp) {
  for (int s = 0; s < 63; s++) {
    uint8_t *sp = fp + 8 + s * 8;

    // TX IQ in Protocol 1 EP2: Left-justified 16-bit I and Q
    // Bytes 0-1: Left (I) sample, big-endian signed 16-bit
    // Bytes 2-3: Right (Q) sample, big-endian signed 16-bit
    int16_t i_raw = (int16_t)((sp[0] << 8) | sp[1]);
    int16_t q_raw = (int16_t)((sp[2] << 8) | sp[3]);

    // Normalize to ±1.0 floating point
    double i_val = i_raw / 32768.0;
    double q_val = q_raw / 32768.0;

    // Push into the ring buffer with 48k→96k upsampling
    tx_iq_push_48k(i_val, q_val);
  }
}

static void handle_command(uint8_t *buf, int len, struct sockaddr_in *sender) {
  if (len < 4 || buf[0] != 0xEF || buf[1] != 0xFE)
    return;

  switch (buf[2]) {
  case 0x02: // Discovery request
  {
    uint8_t reply[64];
    memset(reply, 0, sizeof(reply));
    reply[0] = 0xEF;
    reply[1] = 0xFE;
    reply[2] = 0x02;

    // 0x00 = available, 0x02 = in-use
    int same_client = (sender->sin_addr.s_addr == stream_dest.sin_addr.s_addr);
    reply[3] = (client_active && !same_client) ? 0x02 : 0x00;

    // Fake MAC address & board info (Hermes)
    reply[4] = 0x00;
    reply[5] = 0x1C;
    reply[6] = 0xC0;
    reply[7] = 0xA2;
    reply[8] = 0x22;
    reply[9] = 0x5B;
    reply[10] = 0x06; // Board type
    reply[11] = 0x25; // Protocol version

    sendto(hpsdr_sock, reply, sizeof(reply), 0, (struct sockaddr *)sender, sizeof(*sender));
  } break;

  case 0x04: // Start / stop streaming
    if (buf[3] & 0x01) {
      stream_dest = *sender;
      tx_seq = 0;
      iq_buf_count = 0;
      // Reset TX IQ state on new connection
      tx_iq_wr = 0;
      tx_iq_rd = 0;
      tx_up_prev_i = 0.0;
      tx_up_prev_q = 0.0;
      remote_mox = 0;  // Reset MOX state on new connection
      client_active = 1;
      printf("hpsdr: streaming STARTED to %s:%d\n", inet_ntoa(stream_dest.sin_addr),
             ntohs(stream_dest.sin_port));
    } else {
      client_active = 0;
      printf("hpsdr: streaming STOPPED\n");
      
      // Safety catch: If the client disconnected while transmitting, turn it off
      if (remote_mox) {
          remote_mox = 0;
          g_idle_add(hpsdr_tx_off_idle, NULL);
      }
    }
    break;

  case 0x01: // EP2 host commands
    if (len >= HPSDR_PKT_SIZE) {
      for (int frame = 0; frame < 2; frame++) {
        uint8_t *fp = buf + 8 + frame * 512;
        if (fp[0] != 0x7F || fp[1] != 0x7F || fp[2] != 0x7F)
          continue;

        int c0 = fp[3];
        int addr = (c0 >> 1) & 0x1F;
        int ptt = c0 & 0x01; // bit 0 = MOX from remote app

        // Track remote MOX state and trigger T/R switch (from every frame)
        if (ptt != remote_mox) {
            remote_mox = ptt;
            printf("hpsdr: remote MOX %s\n", remote_mox ? "ON" : "OFF");
        
            // Schedule TX/RX switch on the GTK main thread — bypasses the
            // command queue (can't overflow) and bypasses cw_poll() fighting us
            if (remote_mox)
                g_idle_add(hpsdr_tx_on_idle, NULL);
            else
                g_idle_add(hpsdr_tx_off_idle, NULL);
        
            if (!remote_mox) {
                tx_iq_wr = 0;
                tx_iq_rd = 0;
                tx_up_prev_i = 0.0;
                tx_up_prev_q = 0.0;
            }
        }

        if (addr == 0x02) { // Remote frequency set
          int f = (fp[4] << 24) | (fp[5] << 16) | (fp[6] << 8) | fp[7];
          if (f > 0 && f != freq_hdr) {
            printf("hpsdr: remote set freq %d Hz\n", f);
            char cmd[50];
            sprintf(cmd, "freq %d", f);
            remote_execute(cmd);
          }
        }

        // Only extract TX IQ if *remote* side is actively asserting MOX.
        // Do NOT use `in_tx` here — it lags behind because tx_off() runs
        // asynchronously on the GTK main thread.
        if (remote_mox) {
            extract_tx_iq_from_frame(fp);
        }
      }
    }
    break;
  }
}

static void *hpsdr_poll_thread(void *arg) {
  uint8_t buf[2048];
  struct sockaddr_in sender;
  socklen_t sender_len;

  while (running) {
    sender_len = sizeof(sender);
    int n = recvfrom(hpsdr_sock, buf, sizeof(buf), 0, (struct sockaddr *)&sender, &sender_len);
    if (n > 0) {
      handle_command(buf, n, &sender);
    }
  }
  return NULL;
}

// --- Initialization API -----------------------------------------------------

int hpsdr_init(void) {
  hpsdr_sock = socket(AF_INET, SOCK_DGRAM, 0);
  if (hpsdr_sock < 0)
    return -1;

  int optval = 1;
  setsockopt(hpsdr_sock, SOL_SOCKET, SO_REUSEADDR, &optval, sizeof(optval));
  setsockopt(hpsdr_sock, SOL_SOCKET, SO_BROADCAST, &optval, sizeof(optval));

  struct sockaddr_in addr;
  memset(&addr, 0, sizeof(addr));
  addr.sin_family = AF_INET;
  addr.sin_port = htons(HPSDR_PORT);
  addr.sin_addr.s_addr = htonl(INADDR_ANY);

  if (bind(hpsdr_sock, (struct sockaddr *)&addr, sizeof(addr)) < 0) {
    close(hpsdr_sock);
    hpsdr_sock = -1;
    return -1;
  }

  struct timeval tv = {.tv_sec = 0, .tv_usec = 200000};
  setsockopt(hpsdr_sock, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));

  running = 1;
  return 0;
}

void hpsdr_stop(void) {
  running = 0;
  client_active = 0;

  if (hpsdr_sock >= 0) {
    close(hpsdr_sock);
    hpsdr_sock = -1;
  }
}

int hpsdr_is_connected(void) { return client_active; }

void hpsdr_poll(void) {
  static int started = 0;
  if (!started && running) {
    pthread_create(&poll_thread, NULL, hpsdr_poll_thread, NULL);
    started = 1;
  }
}
